<script lang="ts">
	import Card from "$lib/Card.svelte";
	import type Game from "$lib/models/Game";

	let games: Game[] = [
		{
			id: 1,
			title: "The Legend of Zelda: Breath of the Wild",
			description: "An open-world adventure where Link awakens to save Hyrule from Calamity Ganon.",
			imageUrl: "https://example.com/zelda-botw.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2017-03-03",
			rating: 9.8,
			howLongToBeat: "50-120 hours",
		},
		{
			id: 2,
			title: "Super Mario Odyssey",
			description:
				"Mario travels across diverse worlds to rescue Princess Peach from Bowser’s wedding plans.",
			imageUrl: "https://example.com/mario-odyssey.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2017-10-27",
			rating: 9.5,
			howLongToBeat: "12-60 hours",
		},
		{
			id: 3,
			title: "Hollow Knight",
			description: "Explore a haunting underground world filled with mystery and ancient secrets.",
			imageUrl: "https://example.com/hollow-knight.jpg",
			platform: "PC, Switch, PS4, Xbox",
			releaseDate: "2017-02-24",
			rating: 9.3,
			howLongToBeat: "25-60 hours",
		},
		{
			id: 4,
			title: "Stardew Valley",
			description:
				"Build your dream farm, explore caves, and build relationships in this cozy life sim.",
			imageUrl: "https://example.com/stardew-valley.jpg",
			platform: "PC, Switch, PS4, Xbox, Mobile",
			releaseDate: "2016-02-26",
			rating: 9.0,
			howLongToBeat: "50-200 hours",
		},
		{
			id: 5,
			title: "The Witcher 3: Wild Hunt",
			description:
				"Geralt of Rivia hunts for his adopted daughter across a vast, war-torn fantasy world.",
			imageUrl: "https://example.com/witcher3.jpg",
			platform: "PC, PS4, PS5, Xbox, Switch",
			releaseDate: "2015-05-19",
			rating: 9.9,
			howLongToBeat: "50-150 hours",
		},
		{
			id: 6,
			title: "Celeste",
			description:
				"A challenging platformer about climbing a mountain and overcoming personal struggles.",
			imageUrl: "https://example.com/celeste.jpg",
			platform: "PC, Switch, PS4, Xbox",
			releaseDate: "2018-01-25",
			rating: 9.2,
			howLongToBeat: "8-20 hours",
		},
		{
			id: 7,
			title: "Elden Ring",
			description:
				"An expansive open-world action RPG by FromSoftware featuring deep lore and brutal combat.",
			imageUrl: "https://example.com/elden-ring.jpg",
			platform: "PC, PS4, PS5, Xbox",
			releaseDate: "2022-02-25",
			rating: 9.7,
			howLongToBeat: "60-150 hours",
		},
		{
			id: 8,
			title: "Metroid Prime Remastered",
			description:
				"Revisit Samus Aran’s sci-fi adventure with modern visuals and refined controls.",
			imageUrl: "https://example.com/metroid-prime.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2023-02-08",
			rating: 9.4,
			howLongToBeat: "12-20 hours",
		},
		{
			id: 9,
			title: "Persona 5 Royal",
			description:
				"Lead a group of rebellious students as they change the hearts of corrupt adults.",
			imageUrl: "https://example.com/persona5.jpg",
			platform: "PS4, PS5, PC, Switch, Xbox",
			releaseDate: "2020-03-31",
			rating: 9.7,
			howLongToBeat: "100-130 hours",
		},
		{
			id: 10,
			title: "Animal Crossing: New Horizons",
			description: "Create your own island paradise filled with charming animal neighbors.",
			imageUrl: "https://example.com/animal-crossing-nh.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2020-03-20",
			rating: 9.0,
			howLongToBeat: "100+ hours",
		},
		{
			id: 11,
			title: "Hades",
			description:
				"Battle your way out of the Underworld in this fast-paced roguelike by Supergiant Games.",
			imageUrl: "https://example.com/hades.jpg",
			platform: "PC, Switch, PS4, PS5, Xbox",
			releaseDate: "2020-09-17",
			rating: 9.6,
			howLongToBeat: "20-60 hours",
		},
		{
			id: 12,
			title: "Dark Souls III",
			description: "A dark fantasy action RPG known for its deep lore and punishing combat.",
			imageUrl: "https://example.com/dark-souls-3.jpg",
			platform: "PC, PS4, Xbox",
			releaseDate: "2016-04-12",
			rating: 9.1,
			howLongToBeat: "35-80 hours",
		},
		{
			id: 13,
			title: "Resident Evil 4 Remake",
			description:
				"Leon Kennedy fights to save the president’s daughter in a horrifying European village.",
			imageUrl: "https://example.com/re4-remake.jpg",
			platform: "PC, PS4, PS5, Xbox",
			releaseDate: "2023-03-24",
			rating: 9.5,
			howLongToBeat: "15-30 hours",
		},
		{
			id: 14,
			title: "Cuphead",
			description:
				"A run-and-gun boss rush game with a 1930s cartoon aesthetic and tough gameplay.",
			imageUrl: "https://example.com/cuphead.jpg",
			platform: "PC, Switch, PS4, Xbox",
			releaseDate: "2017-09-29",
			rating: 9.0,
			howLongToBeat: "10-20 hours",
		},
		{
			id: 15,
			title: "Final Fantasy VII Remake",
			description:
				"A modern reimagining of the classic JRPG with stunning visuals and hybrid combat.",
			imageUrl: "https://example.com/ff7-remake.jpg",
			platform: "PS4, PS5, PC",
			releaseDate: "2020-04-10",
			rating: 9.4,
			howLongToBeat: "30-60 hours",
		},
		{
			id: 16,
			title: "DOOM Eternal",
			description: "Rip and tear through hordes of demons in this high-speed FPS sequel.",
			imageUrl: "https://example.com/doom-eternal.jpg",
			platform: "PC, PS4, PS5, Xbox, Switch",
			releaseDate: "2020-03-20",
			rating: 9.3,
			howLongToBeat: "12-25 hours",
		},
		{
			id: 17,
			title: "Undertale",
			description: "A quirky RPG where your choices—whether to fight or show mercy—truly matter.",
			imageUrl: "https://example.com/undertale.jpg",
			platform: "PC, Switch, PS4, Xbox",
			releaseDate: "2015-09-15",
			rating: 9.1,
			howLongToBeat: "6-12 hours",
		},
		{
			id: 18,
			title: "Red Dead Redemption 2",
			description: "An epic Western tale of outlaws, loyalty, and survival in a changing world.",
			imageUrl: "https://example.com/rdr2.jpg",
			platform: "PC, PS4, Xbox",
			releaseDate: "2018-10-26",
			rating: 9.8,
			howLongToBeat: "50-120 hours",
		},
		{
			id: 19,
			title: "God of War: Ragnarök",
			description:
				"Kratos and Atreus face the end of the Norse world in this emotional action epic.",
			imageUrl: "https://example.com/gow-ragnarok.jpg",
			platform: "PS4, PS5",
			releaseDate: "2022-11-09",
			rating: 9.7,
			howLongToBeat: "25-70 hours",
		},
		{
			id: 20,
			title: "Mass Effect Legendary Edition",
			description: "A remastered collection of the Mass Effect trilogy with enhanced visuals.",
			imageUrl: "https://example.com/mass-effect.jpg",
			platform: "PC, PS4, Xbox",
			releaseDate: "2021-05-14",
			rating: 9.0,
			howLongToBeat: "90-150 hours",
		},
		{
			id: 21,
			title: "Tunic",
			description: "A small fox explores an isometric world filled with puzzles and secrets.",
			imageUrl: "https://example.com/tunic.jpg",
			platform: "PC, Switch, PS4, PS5, Xbox",
			releaseDate: "2022-03-16",
			rating: 8.8,
			howLongToBeat: "10-25 hours",
		},
		{
			id: 22,
			title: "Shovel Knight: Treasure Trove",
			description:
				"Retro-inspired platforming adventure filled with charming characters and tight controls.",
			imageUrl: "https://example.com/shovel-knight.jpg",
			platform: "PC, Switch, PS4, Xbox, 3DS",
			releaseDate: "2014-06-26",
			rating: 9.0,
			howLongToBeat: "10-25 hours",
		},
		{
			id: 23,
			title: "Splatoon 3",
			description: "Ink your way to victory in this stylish, colorful multiplayer shooter.",
			imageUrl: "https://example.com/splatoon3.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2022-09-09",
			rating: 8.9,
			howLongToBeat: "20-100 hours",
		},
		{
			id: 24,
			title: "Cyberpunk 2077",
			description: "A futuristic open-world RPG set in the neon city of Night City.",
			imageUrl: "https://example.com/cyberpunk2077.jpg",
			platform: "PC, PS4, PS5, Xbox",
			releaseDate: "2020-12-10",
			rating: 8.8,
			howLongToBeat: "25-100 hours",
		},
		{
			id: 25,
			title: "Super Smash Bros. Ultimate",
			description: "The ultimate crossover fighter featuring every Smash character ever.",
			imageUrl: "https://example.com/ssbu.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2018-12-07",
			rating: 9.6,
			howLongToBeat: "20-200 hours",
		},
		{
			id: 26,
			title: "Fire Emblem: Three Houses",
			description: "Lead your students to victory in tactical battles shaped by moral choices.",
			imageUrl: "https://example.com/fire-emblem-3h.jpg",
			platform: "Nintendo Switch",
			releaseDate: "2019-07-26",
			rating: 9.3,
			howLongToBeat: "60-150 hours",
		},
		{
			id: 27,
			title: "Disco Elysium: The Final Cut",
			description: "A detective RPG focused on dialogue, decisions, and inner turmoil.",
			imageUrl: "https://example.com/disco-elysium.jpg",
			platform: "PC, PS4, PS5, Switch, Xbox",
			releaseDate: "2021-03-30",
			rating: 9.6,
			howLongToBeat: "20-40 hours",
		},
		{
			id: 28,
			title: "Dead Cells",
			description:
				"A fast-paced roguelike action-platformer with fluid combat and endless replayability.",
			imageUrl: "https://example.com/dead-cells.jpg",
			platform: "PC, Switch, PS4, Xbox, Mobile",
			releaseDate: "2018-08-07",
			rating: 9.1,
			howLongToBeat: "15-80 hours",
		},
		{
			id: 29,
			title: "Baldur’s Gate 3",
			description: "A massive D&D-inspired RPG filled with deep storytelling and player freedom.",
			imageUrl: "https://example.com/bg3.jpg",
			platform: "PC, PS5, Xbox",
			releaseDate: "2023-08-03",
			rating: 9.9,
			howLongToBeat: "80-200 hours",
		},
		{
			id: 30,
			title: "Sea of Stars",
			description:
				"A turn-based RPG inspired by classic SNES-era adventures, full of charm and magic.",
			imageUrl: "https://example.com/sea-of-stars.jpg",
			platform: "PC, Switch, PS4, PS5, Xbox",
			releaseDate: "2023-08-29",
			rating: 9.2,
			howLongToBeat: "25-40 hours",
		},
	];
</script>

<div class="cards-container flex flex-row flex-wrap justify-center gap-8 align-middle">
	{#each games as game (game.id)}
		<Card {game} />
	{/each}
</div>
